dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

addons:
  sonarcloud:
    organization: "steguer"

script:
    - pipenv sync
    - pytest --cov simpleinject/ --cov-report xml
    - sonar-scanner

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "NLsvOnzYaizspxpO4CUWKsQp8UWtcwO3XJMZz8Agew5/iZ2vLeWGaW2d88ClrTwP6XNt6Gya3EhdbhMNQb6XWlZ0gp/lbdYhQi9qILv3IjlMfif0ZXi/42gAT63a7+JMf6cNEB0gEapm9jRZ4RNXvPhP3KP9h5fRNilz8Zt4VkS/1cKmtVLrEFuGFCcOwMSLZV+oqAMDkQPqzk4SFzGF+pFHTTYUL0y7lY1uAIJrU2QvITcTcUQBLoRdPwhRjiEnN84Xdx2GuajjL1Gwws78wGEMWVF8XJcYuEaScpAKYtkFiA5bo9lUxz0GhGjxRXZLZATpHK91kRu5u4zWoHeyxY97hzxszrXxT2EsSNbf8+W11wYPkd/hk7wySCLCR8hLW9+uoc4Kk3stFW36C8b/vcJeflIjXKN/ojuQWOLzqqMc3to/Y+Jyz1MpDwcomctqWPBFHolkQDUCXaOvhe0uBS1LFiOsZYV4VkzE4wxCSo6a+Q/jlic6Tz1b/bx1p/fUEChJelexxlb/BWhkXnSM+xG4VPx0Ar7wjF82ikNquN1yYmFVQUwnqsgE24/VVoe82/zHqohYxA8E4qaZIY1JZQRKJpuskhZMsiGTsFfkN+6HpqCs4jBf2aivPlsoFq4CVc/HHbPAElmqKejSwj3BzYC1RAOyHsiSdx0BTGh7qiQ="
  skip_existing: true
  on:
    branch: master
